spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: BING-FIRST-PRODUCTION